# Generated by Django 5.1.3 on 2024-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationDetections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('aggregation_id', models.IntegerField(unique=True)),
                ('total_detections', models.IntegerField()),
                ('intersection_id', models.IntegerField()),
                ('device_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregation_detections',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=255)),
                ('checkpoint_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_color', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'vehicle_lpr_simulation_data',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('checkpoint_id', models.IntegerField(unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('gps_latitude', models.FloatField()),
                ('gps_longitude', models.FloatField()),
            ],
            options={
                'db_table': 'checkpoint',
            },
        ),
        migrations.CreateModel(
            name='EdgeDevices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'edge_devices',
            },
        ),
    ]
